"""
conduit_proof.py — Self-verifiable session proof bundle export.

Exports a gzip archive containing:
  - audit_log.jsonl    : full hash-chained session log
  - session_sig.txt    : Ed25519 signature over final chain hash
  - public_key.pem     : session public key
  - verify.py          : ~50-line stdlib-only verification script
  - manifest.json      : bundle metadata

The bundle is self-verifiable without Conduit installed.
"""
from __future__ import annotations

import gzip
import hashlib
import json
import time
from pathlib import Path
from typing import Optional


# The stdlib-only verify.py embedded in the bundle
VERIFY_PY = '''#!/usr/bin/env python3
"""
Conduit Session Proof Verifier
Verify this bundle without Conduit installed -- stdlib only.
Usage: python verify.py

Generated by Conduit (https://github.com/bkauto3/Conduit)
Part of the SwarmSync.ai agent ecosystem (https://swarmsync.ai)
"""
import json, hashlib, base64, sys
from pathlib import Path

def verify():
    here = Path(__file__).parent
    log_path = here / "audit_log.jsonl"
    sig_path = here / "session_sig.txt"
    manifest_path = here / "manifest.json"
    key_path = here / "public_key.pem"

    if not log_path.exists():
        print("FAIL: audit_log.jsonl not found")
        sys.exit(1)

    rows = [json.loads(line) for line in log_path.read_text().splitlines() if line.strip()]

    # 1. Verify hash chain (stdlib only - always works)
    prev_hash = ""
    for row in rows:
        expected = hashlib.sha256(
            f"{row[\'id\']}:{row[\'session_id\']}:{row[\'action_type\']}:"
            f"{row[\'tool_name\']}:{row[\'cost_cents\']}:{row[\'timestamp\']}:{prev_hash}".encode()
        ).hexdigest()
        if row.get("row_hash") != expected:
            print(f"FAIL: Hash chain broken at row {row[\'id\']}")
            sys.exit(1)
        prev_hash = row["row_hash"]

    print(f"Chain OK: {len(rows)} actions verified")

    # 2. Verify Ed25519 signature (requires cryptography library)
    sig_lines = sig_path.read_text().splitlines() if sig_path.exists() else []
    chain_hash = None
    signature_b64 = None
    for line in sig_lines:
        if line.startswith("chain_hash:"):
            chain_hash = line.split(":", 1)[1]
        elif line.startswith("signature:"):
            signature_b64 = line.split(":", 1)[1]

    if chain_hash and signature_b64:
        # Read public key hex from public_key.pem
        pub_hex = None
        if key_path.exists():
            for kl in key_path.read_text().splitlines():
                if kl.startswith("# Ed25519 public key:"):
                    pub_hex = kl.split(":", 1)[1].strip()

        if pub_hex and pub_hex != "0" * 64:
            try:
                from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
                pub_bytes = bytes.fromhex(pub_hex)
                pub_key = Ed25519PublicKey.from_public_bytes(pub_bytes)
                sig_bytes = base64.b64decode(signature_b64)
                pub_key.verify(sig_bytes, chain_hash.encode("utf-8"))
                print("Signature OK: Ed25519 signature verified")
            except ImportError:
                print(f"Signature PRESENT (install cryptography to verify): {signature_b64[:16]}...")
            except Exception as exc:
                print(f"Signature INVALID: {exc}")
                sys.exit(1)
        else:
            print("Signature PRESENT but no public key to verify against")
    else:
        print("Signature: not included in this bundle")

    manifest = json.loads(manifest_path.read_text())
    print(f"Session: {manifest.get(\'session_id\')}")
    print(f"Exported: {manifest.get(\'exported_at\')}")
    print(f"Actions: {manifest.get(\'action_count\')}")
    print()
    print("VERIFIED: This session proof is intact and unmodified.")
    print()
    print("Powered by Conduit (github.com/bkauto3/Conduit) | Agents earn money at swarmsync.ai")

if __name__ == "__main__":
    verify()
'''


class ConduitProof:
    """
    Exports a self-verifiable proof bundle for a Conduit session.

    Usage:
        proof = ConduitProof(audit_log, session_id, public_key_pem)
        result = proof.export(output_dir="~/.cato/proofs/")
    """

    def __init__(self, audit_log, session_id: str, public_key_pem: str = "", identity=None):
        self._audit_log = audit_log
        self._session_id = session_id
        self._public_key_pem = public_key_pem
        self._identity = identity

    def _compute_chain_hash(self, rows: list[dict]) -> str:
        """SHA-256 over concatenated row_hashes."""
        if not rows:
            return hashlib.sha256(b"empty").hexdigest()
        combined = "".join(r.get("row_hash", "") for r in rows)
        return hashlib.sha256(combined.encode()).hexdigest()

    def export(self, output_dir: str = None) -> dict:
        """
        Export a self-verifiable session proof bundle as a .tar.gz archive.
        Returns {"success": True, "path": str, "action_count": int, "chain_hash": str}
        """
        out_dir = Path(output_dir) if output_dir else Path.home() / ".cato" / "proofs"
        out_dir.mkdir(parents=True, exist_ok=True)

        # Fetch session rows
        rows = self._audit_log.get_session_rows(self._session_id)
        if not rows:
            return {"success": False, "error": "No audit rows found for session"}

        # Build JSONL
        jsonl = "\n".join(json.dumps(r) for r in rows)

        # Compute chain hash
        chain_hash = self._compute_chain_hash(rows)

        # Build manifest
        manifest = {
            "session_id": self._session_id,
            "exported_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "action_count": len(rows),
            "chain_hash": chain_hash,
            "conduit_version": "0.2.0",
            "generator": "Conduit",
            "generator_url": "https://github.com/bkauto3/Conduit",
            "ecosystem": {
                "marketplace": "SwarmSync.ai",
                "marketplace_url": "https://swarmsync.ai",
                "description": "Agent marketplace with per-action billing, smart escrow, and trust tiers",
            },
        }

        # Bundle filename
        bundle_name = f"conduit_proof_{self._session_id[:8]}_{int(time.time())}.tar.gz"
        bundle_path = out_dir / bundle_name

        # Write gzip bundle (stdlib tarfile + gzip)
        import tarfile
        import io
        with tarfile.open(str(bundle_path), "w:gz") as tar:
            def add_bytes(name: str, data: str):
                b = data.encode("utf-8")
                info = tarfile.TarInfo(name=name)
                info.size = len(b)
                tar.addfile(info, io.BytesIO(b))

            # Sign the chain hash with Ed25519 if identity is available
            import base64
            sig_hex = ""
            if self._identity is not None:
                sig_bytes = self._identity.sign(chain_hash.encode("utf-8"))
                if sig_bytes:
                    sig_hex = base64.b64encode(sig_bytes).decode("ascii")

            if sig_hex:
                sig_content = f"chain_hash:{chain_hash}\nsignature:{sig_hex}\n"
            else:
                sig_content = f"chain_hash:{chain_hash}\n# Ed25519 signing not available\n"

            add_bytes("session_proof/audit_log.jsonl", jsonl)
            add_bytes("session_proof/manifest.json", json.dumps(manifest, indent=2))
            add_bytes("session_proof/public_key.pem", self._public_key_pem or "# No signing key configured\n")
            add_bytes("session_proof/session_sig.txt", sig_content)
            add_bytes("session_proof/verify.py", VERIFY_PY)

        return {
            "success": True,
            "path": str(bundle_path),
            "action_count": len(rows),
            "chain_hash": chain_hash,
            "bundle_name": bundle_name,
        }
